#ifndef  _VIRTUALKEYSGAME_H
#define  _VIRTUALKEYSGAME_H

enum class GK_VirtualKey{GK_UNKNOWN = 0,
                         GK_Escape = 200,
                         GK_SysReq,
                         GK_Pause,
                         GK_Space,
                         GK_BackSpace,
                         GK_Delete, // actully passed as ascii
                         GK_Tab,
                         GK_Linefeed,
                         GK_Return,
                         GK_Home,
                         GK_End,
                         GK_Begin,
                         GK_Left,
                         GK_Up,
                         GK_Right,
                         GK_Down,
                         GK_PageUp,
                         GK_PageDown,
                         GK_Select,
                         GK_Insert,
                         GK_Undo,
                         GK_Redo,
                         GK_Menu,
                         GK_Find,
                         GK_Cancel,
                         GK_Break,
                         GK_F1,
                         GK_F2,
                         GK_F3,
                         GK_F4,
                         GK_F5,
                         GK_F6,
                         GK_F7,
                         GK_F8,
                         GK_F9,
                         GK_F10,
                         GK_F11,
                         GK_F12,
                         GK_KPF1,
                         GK_KPF2,
                         GK_KPF3,
                         GK_KPF4,
                         GK_ShiftL,
                         GK_ShiftR,
                         GK_ControlL,
                         GK_ControlR,
                         GK_MetaL,
                         GK_MetaR,
                         GK_AltL,
                         GK_AltR,
                         GK_SuperL,
                         GK_SuperR,
                         GK_HyperL,
                         GK_HyperR,
                         GK_CapsLock,
                         GK_ShiftLock};

#endif  //_VIRTUALKEYSLINUX_H
